k8s_config:
- manifest_path: /yaml
  cluster_info:
    cluster_id: 5f367fe6-02e1-5af3-b947-88f3dbe1e268
    cluster_name: Demo
- manifest_path: /yaml
  cluster_info:
    cluster_id: 5f367fe6-02e1-5af3-b947-88f3dbe1e268
    cluster_name: Demo
