---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      labels:
        app: emoji-svc
        version: v11
    spec:
      serviceAccountName: emoji
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
  annotations:
    a8r.io/description: gRPC API for voting and leaderboard
    a8r.io/owner: "@cakuros"  
    ### Opens slack and shows Daniel Bryant's slack profile
    a8r.io/chat: https://datawire.slack.com/team/U8SPRLSQK
    ### Issues page on application repository
    a8r.io/bugs: "https://github.com/a8r-se/sol-eng-02-emojivoto/issues" 
    ### Goes to Ambassador Labs docs: Log levels and debugging
    a8r.io/logs: https://www.getambassador.io/docs/edge-stack/latest/topics/running/running/#log-levels-and-debugging
    ### Goes to the Ambassdor Labs docs homepage
    a8r.io/documentation: https://se02.mturner.k736.net/docs/
    ### Emojivoto repository
    a8r.io/repository: https://github.com/a8r-se/sol-eng-02-emojivoto  
    ### Ambassador Labs Support Portal Login Page
    a8r.io/support: https://support.datawire.io/hc/en-us  
    ### Ambassador docs debugging page
    a8r.io/runbook: https://www.getambassador.io/docs/latest/topics/running/debugging/ 
    ### Opens Ambassador Docs page "Incident response in Cloud Native World"
    a8r.io/incidents: https://www.getambassador.io/docs/cloud/latest/service-catalog/concepts/ir/#incident-response-in-the-cloud-native-world
    ### Jaeger Trace Boutique App.  Frontend to Shipping & Product Catalog
    a8r.io/uptime: https://monitoring.se02.mturner.k736.net/jaeger/trace/98ab4d0fa605c2f391340c299bfe2ef0  
    ### Login before presenting. In most cases login is cached and not required each time. Username = admin, PW = admin
    a8r.io/performance: https://monitoring.se02.mturner.k736.net/grafana/d/R_NuxHVWk/ambassador-dashboard?refresh=1m&orgId=1  
    a8r.io/dependencies: web-svc.emojivoto, voting-svc.emojivoto
spec:
  selector:
    app: emoji-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
---
