---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      annotations:
        telepresence.getambassador.io/inject-traffic-agent: enabled
        telepresence.getambassador.io/inject-service-name: web-svc
      labels:
        app: web-svc
        version: v11
    spec:
      serviceAccountName: web
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
  annotations:
    a8r.io/description: gRPC API for voting and leaderboard. Lanaguage = Go 
    a8r.io/owner: Daniel Bryant  
    ### Opens slack and shows Daniel Bryant's slack profile
    a8r.io/chat: https://datawire.slack.com/team/U8SPRLSQK
    ### Issues page on application repository
    a8r.io/bugs: https://github.com/a8r-se/sol-eng-02-emojivoto/issues 
    ### Goes to Ambassador Labs docs: Log levels and debugging
    a8r.io/logs: https://www.getambassador.io/docs/edge-stack/latest/topics/running/running/#log-levels-and-debugging
    ### Goes to the Ambassdor Labs docs homepage
    a8r.io/documentation: https://se02.mturner.k736.net/docs/
    ### Emojivoto repository
    a8r.io/repository: https://github.com/a8r-se/sol-eng-02-emojivoto  
    ### Ambassador Labs Support Portal Login Page
    a8r.io/support: https://support.datawire.io/hc/en-us  
    ### Ambassador docs debugging page
    a8r.io/runbook: https://www.getambassador.io/docs/latest/topics/running/debugging/ 
    ### Opens Ambassador Docs page "Incident response in Cloud Native World"
    a8r.io/incidents: https://www.getambassador.io/docs/cloud/latest/service-catalog/concepts/ir/#incident-response-in-the-cloud-native-world
    ### Jaeger Trace Boutique App.  Frontend to Shipping & Product Catalog
    a8r.io/uptime: https://monitoring.se02.mturner.k736.net/jaeger/trace/98ab4d0fa605c2f391340c299bfe2ef0  
    ### Login before presenting. In most cases login is cached and not required each time. Username = admin, PW = admin
    a8r.io/performance: https://monitoring.se02.mturner.k736.net/grafana/d/R_NuxHVWk/ambassador-dashboard?refresh=1m&orgId=1  
    a8r.io/dependencies: voting-svc.emojivoto, emoji-svc.emojivoto
    ### ArgoRollOuts Annotations
    a8r.io/rollouts.scm.branch: main
    a8r.io/rollouts.scm.path: yaml/emoji-web  
    a8r.io/rollouts.image-repo.type: dockerhub
    a8r.io/rollouts.image-repo.name: caseykurosawa/emojivoto-web
    a8r.io/rollouts.deployment: web
    a8r.io/rollouts.mappings: emojivoto-mapping
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-svc
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: emojivoto-amb-labs-io
  namespace: emojivoto
spec:
  acmeProvider:
    email: caseykurosawa@datawire.io
  hostname: "emojivoto.amb-labs.io"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: emoji-web-mapping
  namespace: emojivoto
spec:
  hostname: "emojivoto.amb-labs.io"
  prefix: /
  service: web-svc.emojivoto:80