apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-mapping-1666982668552
  namespace: default
spec:
  service: quote.default:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: "*"
  prefix: /backend/
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimit
metadata:
  name: rate-limit-for-quote-mapping-1666982668552
  namespace: default
spec:
  domain: ambassador
  limits:
  - action: Enforce
    pattern:
    - generic_key: quote-mapping-1666982668552
    - remote_address: "*"
    rate: 50
    unit: minute
    burstFactor: 1
