---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-amb-labs-io
  namespace: default
spec:
  acmeProvider:
    email: caseykurosawa@datawire.io
  hostname: "example.amb-labs.io"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  hostname: "example.amb-labs.io"
  prefix: /quote/
  service: quote.default:80
